name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Lock npm version
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.0

      - name: Install specific pnpm version
        run: npx pnpm@7.32.0 install # 使用 npx 安装特定版本的 pnpm
      - name: Install dependencies
        run: npx pnpm@7.32.0 install # 使用 npx 运行特定版本的 pnpm
      - name: Build project
        run: npx pnpm@7.32.0 run build # 使用 npx 运行特定版本的 pnpm

      - name: Install and Build
        run: |
          npm i -g pnpm
          pnpm run init
          pnpm run build:doc
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          BRANCH: gh-pages
          FOLDER: dist
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
